// <auto-generated />
namespace WikiAPI.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SwaggerAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SwaggerAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "202112132124596_SwaggerAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
